sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
